server:
  port: 8082

spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      routes:
        - id: ai-server
          uri: lb://OLLAMA-EMBEDDING-SERVER
          predicates:
            - Path=/ai/**
#            - Path=/api/project/**
#            - Path=/api/embeded-group/**

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:192.168.0.55}:${EUREKA_PORT:8081}/eureka/


